name: Twitter Digest

on:
  schedule:
    - cron: '0 12 * * *'  # Runs at 12 PM UTC daily
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and run Docker container
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        run: |
          docker build -t twitter-digest .
          docker run --rm \
            -e SENDGRID_API_KEY=$SENDGRID_API_KEY \
            -e RECIPIENT_EMAIL=$RECIPIENT_EMAIL \
            twitter-digest 